### ISSUE TITLE
return values are ff 

### ISSUE THREAD

**Issue by sheldon123z** [kentavv/tidbits#1]
Hi @kentavv,

Thanks for your code. I used a different board with a similar I2C interface. My sensor gives me 0xff values for all 6 bytes, I am pretty sure that I used the correct command sequence, do you know why that will happen?

Best
Sheldon

**Comment by kentavv** [comment]
Hi @sheldon123z 
This sounds like an electrical issue. Do you have an oscilloscope that you can use to check the signal quality? I think the board I tested with has internal termination. Perhaps yours does not?

**Comment by sheldon123z** [comment]
Hi @kentavv, 

Thanks for your reply. I fixed the problem by correcting the sequence messages sent to the sensor. 

Best

**Comment by kentavv** [comment]
Hi @sheldon123z 
Do I need to make a change to the code?
Thank you

**Comment by sheldon123z** [comment]
Hi @kentavv 
I didn't run the code, but I think it is fine.
